### ISSUE TITLE
Title is optional

### ISSUE THREAD

**Issue by srid** [Gabriel439/political-notes#1]
Hiya! Just stumbled across this repo, and it is interesting to see that you use [title IDs](https://neuron.zettel.page/id.html). Not sure if you already knew, but if you use title IDs, then specifying a title is ... not required. 

Take this note for example, https://github.com/Gabriel439/political-notes/blob/master/prefer%20approval%20voting%20over%20ranked-choice%20voting.md

You can remove the H1 title from the note, and rename the file to `Prefer approval voting over ranked-choice voting.md` (basically you change the case of the first letter in the filename). The title remains effectively the same, as neuron infers it from the filename. 

Just wanted to let you know; feel free to close this issue eitherway.

**Comment by srid** [comment]
cf. https://github.com/srid/r-ScientificNutrition

**Comment by Gabriella439** [comment]
@srid: Thanks for the tip! 🙂
